name: Dispatch to site

on:
  workflow_dispatch:
  page_build:
  push:
    branches:
      - gh-pages

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Push to site
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: "Tommoa/site"
          event-type: update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "module": "static/ozgrav-research", "branch": "gh-pages"}'
