name: Build PDFs

on: [push]

jobs:
  proposal:
    name: Build my research proposal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          output/proposal.pdf
        key: proposal-${{ hashFiles('proposal/**') }}
    - uses: Tommoa/tectonic-fontawesome-action@master
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        tex_path: proposal/proposal.tex
    - name: Rename
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
          mkdir output
          mv proposal/proposal.pdf output/
          cp README.md output/index.md
    - uses: actions/upload-artifact@v1
      with:
        name: proposal.pdf
        path: output/proposal.pdf
    - name: Deploy to GitHub Pages
      if: steps.cache.outputs.cache-hit != 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./output
        allow_empty_commit: false
        keep_files: true
  progress-report:
    name: Build progress report
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          output/progress-2020-05-29.pdf
        key: proposal-${{ hashFiles('progress-report/**') }}
    - uses: Tommoa/tectonic-fontawesome-action@master
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        tex_path: progress-report/report.tex
    - name: Rename
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
          mkdir output
          mv progress-report/report.pdf output/progress-2020-05-29.pdf
          cp README.md output/index.md
    - uses: actions/upload-artifact@v1
      with:
        name: progress-2020-05-29.pdf
        path: output/progress-2020-05-29.pdf
    - name: Deploy to GitHub Pages
      if: steps.cache.outputs.cache-hit != 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./output
        allow_empty_commit: false
        keep_files: true
  analysis:
    name: Build complexity analysis report
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          output/analysis.pdf
        key: proposal-${{ hashFiles('analysis/**') }}
    - uses: Tommoa/tectonic-fontawesome-action@master
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        tex_path: analysis/analysis.tex
    - name: Rename
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
          mkdir output
          mv analysis/analysis.pdf output/analysis.pdf
          cp README.md output/index.md
    - uses: actions/upload-artifact@v1
      with:
        name: analysis.pdf
        path: output/analysis.pdf
    - name: Deploy to GitHub Pages
      if: steps.cache.outputs.cache-hit != 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./output
        allow_empty_commit: false
        keep_files: true
