name: Build PDF

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Tectonic and FontAwesome
      run: |
          docker build . -t tectonic
    - name: Build
      run: |
          docker run -v $PWD:/usr/src/tex tectonic:latest proposal/proposal.tex
    - name: Rename
      run: |
          mkdir output
          mv proposal/proposal.pdf output/
          cp README.md output/index.md
    - uses: actions/upload-artifact@v1
      with:
        name: proposal.pdf
        path: output/proposal.pdf
    - name: Deploy to gh-pages branch
      uses: docker://peaceiris/gh-pages:latest
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./output
      with:
        emptyCommits: false
