name: Build PDFs

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build LaTeX papers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: 
        - abstract
        - analysis
        - dissertation
        - progress-report
        - proposal
        - seminar-presentation
        - seminar-talk
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          output/${{ matrix.path }}.pdf
        key: ${{ matrix.path }}-${{ hashFiles(matrix.path) }}
    - uses: Tommoa/tectonic-fontawesome-action@master
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        tex_path: ${{ matrix.path }}/main.tex
    - name: Rename
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir output
        mv ${{ matrix.path }}/main.pdf output/${{ matrix.path }}.pdf
        cp README.md output/index.md
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.path }}.pdf
        path: output/${{ matrix.path }}.pdf
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with: 
        path: artifacts
    - name: Move PDFs
      run: |
        mkdir -p output
        mv artifacts/*/*.pdf output
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
